import { createSlice } from "@reduxjs/toolkit";
import { initialState } from "./types";
import { fetchActivitiesStats } from "./actions";

export const activitiesStatsSlice = createSlice({
  name: "activitiesStats",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchActivitiesStats.pending, (state) => {
        state.fetchStatus = "loading";
      })
      .addCase(fetchActivitiesStats.fulfilled, (state, action) => {
        state.fetchStatus = "succeeded";
        state.activitiesStats = action.payload;
      })
      .addCase(fetchActivitiesStats.rejected, (state, action) => {
        state.fetchStatus = "failed";
        state.error = action.error.message;
      });
  },
});

export default activitiesStatsSlice.reducer;
