import { createSlice } from "@reduxjs/toolkit";
import { initialState } from "./types";
import { fetchActivities, postActivity, deleteActivity } from "./actions";

export const activitiesSlice = createSlice({
  name: "activities",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchActivities.pending, (state) => {
        state.fetchStatus = "loading";
      })
      .addCase(fetchActivities.fulfilled, (state, action) => {
        state.fetchStatus = "succeeded";
        state.activities = action.payload;
      })
      .addCase(fetchActivities.rejected, (state, action) => {
        state.fetchStatus = "failed";
        state.error = action.error.message;
      })
      .addCase(postActivity.pending, (state) => {
        state.operationStatus = "loading";
      })
      .addCase(postActivity.fulfilled, (state, action) => {
        state.operationStatus = "succeeded";
        state.activities.push(action.payload);
      })
      .addCase(postActivity.rejected, (state, action) => {
        state.operationStatus = "failed";
        state.error = action.error.message;
      })
      .addCase(deleteActivity.pending, (state) => {
        state.operationStatus = "loading";
      })
      .addCase(deleteActivity.fulfilled, (state, action) => {
        state.operationStatus = "succeeded";
        state.activities = state.activities.filter(
          (a) => a.id !== action.meta.arg.id
        );
      })
      .addCase(deleteActivity.rejected, (state, action) => {
        state.operationStatus = "failed";
        state.error = action.error.message;
      });
  },
});

export default activitiesSlice.reducer;
